[package]
name = "aurora_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
once_cell = "1.15.0"
sqlparser = "0.25.0"

[dependencies.aurora_util]
path = "../aurora-util"
